[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dspy"
dynamic = ["version"]
description = 'Python Library with many data structures that I wish I had easy access to'
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
keywords = []
authors = [
  { name = "Harsh Parekh", email = "harsh_parekh@outlook.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = []

[project.optional-dependencies]
vectorize = ["numpy"]

[project.urls]
Documentation = "https://github.com/unknown/dspy#readme"
Issues = "https://github.com/unknown/dspy/issues"
Source = "https://github.com/unknown/dspy"

[tool.hatch.version]
path = "src/dspy/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
]
features = [
  "vectorize"
]

[tool.hatch.envs.default.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "test-cov",
  "cov-report",
]

[[tool.hatch.envs.all.matrix]]
python = ["3.13"]

[tool.hatch.envs.types]
dependencies = [
  "ty>=0.0.36",
]
[tool.hatch.envs.types.scripts]
check = "ty check {args:src/dspy tests}"
watch = "ty check --watch {args:src/dspy tests}"

[tool.hatch.envs.hatch-static-analysis]
config-path = "pyproject.toml"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D211",  # no-blank-line-before-class
  "D213",  # multi-line-summary-second-line
]

[tool.coverage.run]
source_pkgs = ["dspy", "tests"]
branch = true
parallel = true
omit = [
  "src/dspy/__about__.py",
]

[tool.coverage.paths]
dspy = ["src/dspy", "*/dspy/src/dspy"]
tests = ["tests", "*/dspy/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
